version: '3.7'
services:
  app:
    image: web-pontos:beta
    container_name: web-pontos-beta
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    ports:
      - '85:80'
    restart: always
    environment:
      HOST: 0.0.0.0
